# Generated by Django 6.0.5 on 2026-05-21 02:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Protein',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protein_id', models.CharField(db_index=True, max_length=10, unique=True)),
                ('title', models.CharField(max_length=500)),
                ('score', models.FloatField(default=0)),
                ('view_url', models.URLField()),
                ('download_url', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProteinSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProteinDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classification', models.CharField(blank=True, max_length=255)),
                ('organism', models.CharField(blank=True, max_length=255)),
                ('expression_system', models.CharField(blank=True, max_length=255)),
                ('full_title', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('protein', models.OneToOneField(db_column='protein_id', on_delete=django.db.models.deletion.CASCADE, related_name='details', to='core.protein', to_field='protein_id')),
            ],
        ),
        migrations.CreateModel(
            name='ProteinPDBFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdb_content', models.TextField()),
                ('downloaded_at', models.DateTimeField(auto_now_add=True)),
                ('protein', models.OneToOneField(db_column='protein_id', on_delete=django.db.models.deletion.CASCADE, related_name='pdb_file', to='core.protein', to_field='protein_id')),
            ],
        ),
        migrations.AddField(
            model_name='protein',
            name='search',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proteins', to='core.proteinsearch'),
        ),
    ]
